### ISSUE TITLE
Handling of finished, but never operational power plants

### ISSUE THREAD

**Issue by melgu** [cristianst85/GeoNuclearData#3]
How do you handle power plants, which finished construction, but never started operating?
Two examples I can think of are [Zwentendorf](http://www.zwentendorf.com) and [SNR-300 (Kalkar)](https://en.wikipedia.org/wiki/SNR-300). Both are finished reactors, but missing from the database. The former is now a museum and the latter an amusement park.

**Comment by cristianst85** [comment]
Hello @melgu!

It seems that I don't have a corresponding status for those examples you have provided.

I was thinking of adding a new status **Never Commissioned** (or **Never Operated** / **Never Used** / **Never Connected to Grid**).

IAEA uses the [never commissioned](https://nucleus.iaea.org/sites/gsan/news/Pages/Zwentendorf-Plant-Walkdown.aspx) term.

Regarding **SNR-300** the same could apply even if its reactor was taken into partial operation because the existing **Operational** status refers to _commercial operation_ (or _connection to the grid_).

**Comment by melgu** [comment]
Sounds good 👍

**Comment by cristianst85** [comment]
I did more digging and I found that in the [PRIS ](https://pris.iaea.org/PRIS/home.aspx) database (IAEA) both **Zwentendorf** and **Kalkar** NPPs are listed as **Cancelled Construction** which I don't think it's really accurate.

![image](https://user-images.githubusercontent.com/12585988/107861101-1db67a00-6e4c-11eb-91ea-e41bb3d67e2e.png)

![image](https://user-images.githubusercontent.com/12585988/107861097-18f1c600-6e4c-11eb-8695-0dc6ae754b2e.png)

According to this [report](https://www.actu-environnement.com/media/pdf/rapport-nucleaire-monde-2016.pdf) (pages 33-34), there were 92 cancelled or suspended reactor constructions between 1977 and July 2016. As far I can tell most of those reactors are currently missing from this database.

**Comment by cristianst85** [comment]
I have added both NPPs to the database (see [0.17.4](https://github.com/cristianst85/GeoNuclearData/releases/tag/0.17.4) release notes). You can close this issue if you think it has been addressed.

Thanks again for reporting this.

**Comment by melgu** [comment]
Thank you so much for all the work you put in. This is amazing!
